language: objective-c
osx_image: xcode7.2
sudo: false

env:
  global:
    - WORKSPACE=Xcode/Project.xcworkspace
    - IOS_DEVICE_SDK=iphoneos9.2
    - IOS_SIMULATOR_SDK=iphonesimulator9.2
  matrix:
    - POD_LINT="yes"
    - SDK="$IOS_DEVICE_SDK"    SCHEME="All"                     CONFIGURATION="Debug"
    - SDK="$IOS_DEVICE_SDK"    SCHEME="All"                     CONFIGURATION="Release" SWIFT_OPTIMIZATION_LEVEL="-O"
    - SDK="$IOS_DEVICE_SDK"    SCHEME="All"                     CONFIGURATION="Release" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="All"                     CONFIGURATION="Debug"   DESTINATION="OS=8.2,name=iPhone 4S"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="All"                     CONFIGURATION="Release" DESTINATION="OS=9.2,name=iPhone 6S" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-CoreGraphics" CONFIGURATION="Debug"   DESTINATION="OS=9.2,name=iPhone 6S"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-CoreGraphics" CONFIGURATION="Release" DESTINATION="OS=9.2,name=iPhone 6S" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-Foundation"   CONFIGURATION="Debug"   DESTINATION="OS=9.2,name=iPhone 6S"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-Foundation"   CONFIGURATION="Release" DESTINATION="OS=9.2,name=iPhone 6S" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-Swift"        CONFIGURATION="Debug"   DESTINATION="OS=9.2,name=iPhone 6S"
    - SDK="$IOS_SIMULATOR_SDK" SCHEME="Extensions-Swift"        CONFIGURATION="Release" DESTINATION="OS=9.2,name=iPhone 6S" SWIFT_OPTIMIZATION_LEVEL="-Owholemodule"
    
before_install:
  - gem install cocoapods xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - cd Xcode && pod update --no-repo-update && cd ..
  - if [ $POD_LINT == "yes" ]; then
      pod lib lint --allow-warnings --quick --verbose;
    elif [ $SDK == $IOS_DEVICE_SDK ]; then
      xcodebuild build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -configuration "$CONFIGURATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty;
    else
      xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration "$CONFIGURATION" | xcpretty;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      secure: O1mImcr+B50sT8mcrY5BbO2WKVfXXIwAGXTH0qgOjR1OEEaJWcg5xrkJbyO55DQEAMsoqaupA5DgFEgShGHZ94HWyr30z6qlCO/CEC9+syRV9vLV/s0CEmnGJDMCSK6gYqwcJsk7S1iawPWRVOPjt8QUZ7O5+c/mrfUitlf2BOY=
    on_success: change
    on_failure: always
    on_start:   never
